;[pytest]
;addopts =
;    --browser=chromium
;    --output=test-results
;    --screenshot=only-on-failure
;    --video=retain-on-failure
;    --tracing=retain-on-failure
;    --alluredir allure-results
;    --clean-alluredir
;markers =
;    smoke: szybkie testy krytyczne
;    api: szybkie testy api
